[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel"]  # PEP 508 specifications.
build-backend = "setuptools.build_meta"

[project]
name ="raft"
version = "0.0"

[tool.setuptools.packages.find]
where = ["src"]