[build-system]
# Minimum requirements for the build system to execute.
requires = ["setuptools", "wheel"]  # PEP 508 specifications.

[project]
name ="derp"
version = "0.0"

[tool.setuptools.packages.find]
where = ["core", "alt_cuda_corr"]